sudo: required
before_install:
- "./install-protobuf.sh"
language: java
jdk: oraclejdk7
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pproduction
- mvn test -B
deploy:
  provider: s3
  access_key_id:
    secure: OTZ1vUSx1+EdhAZ4jIqoGcmC4tfRap+cpQxaIaO6Ux41Zj45NJ9ZMRVd/9HzOWHiGTHBcQUZ/qZcZBzDNujXB2AWgiGtrkRsbH5e6x2eVJZgTsZDf8KM0S1hn9JjZ1HzrZUGcicns7WHAyi+75rsKbNMjlOFWmVDyZKgDv7LUJw=
  secret_access_key:
    secure: HsAWCzoTBVw7VIH1ItiDLtBRRyrNDpyXJo4syq4T9wV3H6TeqUIbSe0AbEwGrZoLZoKrNF4m+c1y9rAHcaov4Brj8mwPoFadBkRyEDu8Z1Gx9NLmMRT5BxHaeu3wd9NDUdrkZxXVI7uOlHQv37jArZBX4fgYR3Qa3q1RIZEFVnk=
  bucket: oss.forter.com
  local-dir: "/home/travis/.m2/repository/com/forter/riemann-java-client/"
  upload-dir: repository/com/forter/riemann-java-client
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
