sudo: required
before_install:
- "./install-protobuf.sh"
language: java
jdk: oraclejdk7
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pproduction
- mvn test -B
deploy:
  provider: s3
  access_key_id:
    secure: izTJZk+6mGiTeja30d7/4FqAlrPUAqBW7LgYOfp18hVl6IWt85nXkdgCcUdYuNGGGmIwQIt/JlPAUpvoiU+RrLyrAj88VjLLz3H+JGQKfkNzOXin5d2EvNgyiibgs96fyTJ5nMwT/XGf65IR8V8IIbl9UXFyWM1ZXNBcIlQQu1Q=
  secret_access_key:
    secure: ZSgPRJYrYRuDlzHiquRZMtjUYyPKKvmY4GtmlQq3/gLOravH2YiOnL9Wfmidr+ZMTb2v9b52rPe383HepiyfE4Tz0Lw4o55uHCEzdW0A/C/dZ5C3Ut/ocVGIsTrnNFo5fwdkS2/Vx6PyVn9JIt8awg07ITLzEKZ4UMfpegAq2R0=
  bucket: oss.forter.com
  local-dir: "/home/travis/.m2/repository/com/forter/riemann-java-client/"
  upload-dir: repository/com/forter/riemann-java-client
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
