language: java
jdk: oraclejdk7
before_install:
- sudo apt-get update -qq
- ./install_protobuf.sh
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pproduction
- mvn test -B
deploy:
  provider: s3
  access_key_id:
    secure: A8DvZTJaaS/+TJDptSN/txQViLz07ETMMYBzAGkoSfeepSTiT43ELpUIqA1v+0Dl69Fdvx9BCvBm535X+X3B52JrVsI57HcUzq+RsS2zv483Tp/b9nnb0//iR5232Xurf1NmrH+JDBM+xkNadB0bt3bSB3Qwdqxl9uijEEuYzUs=
  secret_access_key:
    secure: JfMLTdUlRsllKxu9jy5eGB60WTAfvRns3iaAde92FBvxjcD33LYbuLzSriwxEHOcLKLSQH4c6Bjf5H89mKihJCTRHctHjPsdjNn/XEnfPbk75+nLmvCn1eQHFncsACZFdF8Sa9SZ5jn3PBK0kuPEZBIFq/gpNoZjmQo9GKwX26Y=
  bucket: oss.forter.com
  local-dir: /home/travis/.m2/repository/com/forter/riemann-java-client/
  upload-dir: repository/com/forter/riemann-java-client
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
